vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       profile_image:
           uri_prefix: '%profile_image%'
           upload_destination: '%kernel.project_dir%/public%profile_image%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: true

       upload_file:
           uri_prefix: '%upload_file%'
           upload_destination: '%kernel.project_dir%/public%upload_file%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: true  